# -*- coding: utf-8 -*-
import subprocess

# ════════════════════════════════════
# 1. Створюємо terminal-log.js
# ════════════════════════════════════
TERMINAL_JS = (
    "'use strict';\n\n"
    "/* ══════════════════════════════════════════\n"
    "   Terminal Log — показує всі команди і відповіді\n"
    "   Не чіпає існуючий код — тільки перехоплює\n"
    "   ══════════════════════════════════════════ */\n\n"

    "window.TermLog = {\n"
    "  _entries: [],\n"
    "  _visible: false,\n"
    "  _el: null,\n"
    "  _bodyEl: null,\n"
    "  _maxEntries: 200,\n\n"

    "  /* ── Ініціалізація ── */\n"
    "  init: function() {\n"
    "    if (document.getElementById('termlog-panel')) return;\n\n"
    "    /* Кнопка-тоглер */\n"
    "    var btn = document.createElement('div');\n"
    "    btn.id = 'termlog-btn';\n"
    "    btn.innerHTML = '⌨ Лог команд <span id=\"termlog-count\" style=\"background:#c03030;color:#fff;border-radius:10px;padding:1px 6px;font-size:10px;margin-left:4px;display:none;\">0</span>';\n"
    "    btn.style.cssText = [\n"
    "      'position:fixed', 'bottom:0', 'left:50%', 'transform:translateX(-50%)',\n"
    "      'background:#0d1117', 'border:1px solid #2a3b48',\n"
    "      'border-bottom:none', 'border-radius:8px 8px 0 0',\n"
    "      'padding:5px 18px', 'cursor:pointer', 'z-index:888888',\n"
    "      'color:#5fd0a5', 'font-size:12px', 'font-weight:600',\n"
    "      'user-select:none', 'display:flex', 'align-items:center', 'gap:4px',\n"
    "    ].join(';');\n"
    "    document.body.appendChild(btn);\n"
    "    btn.onclick = function() { TermLog.toggle(); };\n\n"

    "    /* Панель термінала */\n"
    "    var panel = document.createElement('div');\n"
    "    panel.id = 'termlog-panel';\n"
    "    panel.style.cssText = [\n"
    "      'position:fixed', 'bottom:0', 'left:0', 'right:0',\n"
    "      'height:320px', 'background:#060d10',\n"
    "      'border-top:2px solid #1a3a2a',\n"
    "      'z-index:888887', 'display:none',\n"
    "      'flex-direction:column',\n"
    "    ].join(';');\n\n"

    "    panel.innerHTML =\n"
    "      '<div id=\"termlog-header\" style=\"display:flex;align-items:center;justify-content:space-between;' +\n"
    "        'padding:6px 14px;background:#0d1117;border-bottom:1px solid #1a2a38;flex-shrink:0;\">'+\n"
    "        '<div style=\"display:flex;align-items:center;gap:10px;\">'+\n"
    "          '<span style=\"color:#5fd0a5;font-weight:700;font-size:13px;\">⌨ Terminal Log</span>'+\n"
    "          '<span id=\"termlog-router\" style=\"color:#4a6070;font-size:11px;\"></span>'+\n"
    "        '</div>'+\n"
    "        '<div style=\"display:flex;gap:8px;\">'+\n"
    "          '<button id=\"termlog-clear\" style=\"background:transparent;border:1px solid #2a3b48;' +\n"
    "            'color:#4a6070;border-radius:5px;padding:2px 10px;cursor:pointer;font-size:11px;\">🗑 Очистити</button>'+\n"
    "          '<button id=\"termlog-copy-all\" style=\"background:transparent;border:1px solid #2a3b48;' +\n"
    "            'color:#4a6070;border-radius:5px;padding:2px 10px;cursor:pointer;font-size:11px;\">📋 Копіювати все</button>'+\n"
    "          '<button id=\"termlog-close\" style=\"background:transparent;border:1px solid #2a3b48;' +\n"
    "            'color:#4a6070;border-radius:5px;padding:2px 10px;cursor:pointer;font-size:11px;\">✕</button>'+\n"
    "        '</div>'+\n"
    "      '</div>'+\n"
    "      '<div id=\"termlog-body\" style=\"flex:1;overflow-y:auto;padding:8px 14px;' +\n"
    "        'font-family:monospace;font-size:12px;line-height:1.6;\"></div>'+\n"
    "      '<div id=\"termlog-input-bar\" style=\"display:flex;gap:8px;padding:6px 14px;' +\n"
    "        'border-top:1px solid #1a2a38;background:#0a1218;flex-shrink:0;\">'+\n"
    "        '<span style=\"color:#5fd0a5;\">❯</span>'+\n"
    "        '<input id=\"termlog-cmd-input\" type=\"text\" placeholder=\"Виконати команду на роутері...\" '+\n"
    "          'style=\"flex:1;background:transparent;border:none;outline:none;' +\n"
    "          'color:#e6edf3;font-family:monospace;font-size:12px;\">'+\n"
    "        '<button id=\"termlog-run\" style=\"background:#1a3a2a;border:1px solid #2a5a3a;' +\n"
    "          'color:#5fd0a5;border-radius:5px;padding:2px 12px;cursor:pointer;font-size:11px;\">▶ Run</button>'+\n"
    "        '<button id=\"termlog-export-read\" style=\"background:#1a2a3a;border:1px solid #2a3a5a;' +\n"
    "          'color:#5b9bd5;border-radius:5px;padding:2px 12px;cursor:pointer;font-size:11px;\">📄 Читати export</button>'+\n"
    "      '</div>';\n\n"

    "    document.body.appendChild(panel);\n"
    "    TermLog._el     = panel;\n"
    "    TermLog._bodyEl = document.getElementById('termlog-body');\n\n"

    "    /* Listeners */\n"
    "    document.getElementById('termlog-close').onclick    = function() { TermLog.hide(); };\n"
    "    document.getElementById('termlog-clear').onclick    = function() { TermLog.clear(); };\n"
    "    document.getElementById('termlog-copy-all').onclick = function() { TermLog.copyAll(); };\n"
    "    document.getElementById('termlog-run').onclick      = function() { TermLog.runManual(); };\n"
    "    document.getElementById('termlog-export-read').onclick = function() { TermLog.readExport(); };\n\n"

    "    /* Enter в input */\n"
    "    document.getElementById('termlog-cmd-input').addEventListener('keydown', function(e) {\n"
    "      if (e.key === 'Enter') TermLog.runManual();\n"
    "      /* Стрілки — історія команд */\n"
    "      if (e.key === 'ArrowUp') {\n"
    "        TermLog._histIdx = Math.max(0, (TermLog._histIdx || 0) - 1);\n"
    "        this.value = TermLog._history[TermLog._histIdx] || '';\n"
    "        e.preventDefault();\n"
    "      }\n"
    "      if (e.key === 'ArrowDown') {\n"
    "        TermLog._histIdx = Math.min((TermLog._history||[]).length,\n"
    "          (TermLog._histIdx || 0) + 1);\n"
    "        this.value = TermLog._history[TermLog._histIdx] || '';\n"
    "        e.preventDefault();\n"
    "      }\n"
    "    });\n\n"

    "    /* Resize handle */\n"
    "    var header = document.getElementById('termlog-header');\n"
    "    var resizing = false, startY, startH;\n"
    "    header.style.cursor = 'ns-resize';\n"
    "    header.addEventListener('mousedown', function(e) {\n"
    "      if (e.target.tagName === 'BUTTON') return;\n"
    "      resizing = true;\n"
    "      startY = e.clientY;\n"
    "      startH = panel.offsetHeight;\n"
    "      e.preventDefault();\n"
    "    });\n"
    "    document.addEventListener('mousemove', function(e) {\n"
    "      if (!resizing) return;\n"
    "      var newH = startH - (e.clientY - startY);\n"
    "      panel.style.height = Math.max(120, Math.min(window.innerHeight * 0.8, newH)) + 'px';\n"
    "    });\n"
    "    document.addEventListener('mouseup', function() { resizing = false; });\n\n"

    "    TermLog._history = [];\n"
    "    TermLog._histIdx = 0;\n"
    "    console.log('[TermLog] Ready ✅');\n"
    "  },\n\n"

    "  /* ── Показати/Сховати ── */\n"
    "  toggle: function() {\n"
    "    if (TermLog._visible) TermLog.hide();\n"
    "    else TermLog.show();\n"
    "  },\n"
    "  show: function() {\n"
    "    if (!TermLog._el) TermLog.init();\n"
    "    TermLog._el.style.display = 'flex';\n"
    "    TermLog._visible = true;\n"
    "    /* Оновлюємо назву роутера */\n"
    "    var r = window.getActiveRouter ? window.getActiveRouter() : null;\n"
    "    var rEl = document.getElementById('termlog-router');\n"
    "    if (rEl && r) rEl.textContent = '@ ' + (r.ip||r.host||'');\n"
    "    TermLog.scrollBottom();\n"
    "    setTimeout(function() {\n"
    "      var inp = document.getElementById('termlog-cmd-input');\n"
    "      if (inp) inp.focus();\n"
    "    }, 100);\n"
    "  },\n"
    "  hide: function() {\n"
    "    if (TermLog._el) TermLog._el.style.display = 'none';\n"
    "    TermLog._visible = false;\n"
    "  },\n\n"

    "  /* ── Додати запис ── */\n"
    "  log: function(type, text, extra) {\n"
    "    if (!TermLog._bodyEl) TermLog.init();\n"
    "    var ts = new Date().toLocaleTimeString('uk-UA');\n"
    "    var colors = {\n"
    "      cmd:     { bg: '#0a1a0a', border: '#2a5a3a', icon: '❯', color: '#5fd0a5' },\n"
    "      ok:      { bg: '#0a1a10', border: '#1a4a2a', icon: '✅', color: '#4ab890' },\n"
    "      error:   { bg: '#1a0a0a', border: '#5a2a2a', icon: '❌', color: '#e08080' },\n"
    "      info:    { bg: '#0a0f1a', border: '#2a3a5a', icon: 'ℹ', color: '#5b9bd5' },\n"
    "      warning: { bg: '#1a1200', border: '#4a3a00', icon: '⚠️', color: '#f0a840' },\n"
    "    };\n"
    "    var s = colors[type] || colors.info;\n"
    "    var entry = document.createElement('div');\n"
    "    entry.style.cssText = [\n"
    "      'background:' + s.bg,\n"
    "      'border-left:3px solid ' + s.border,\n"
    "      'border-radius:0 4px 4px 0',\n"
    "      'padding:4px 10px',\n"
    "      'margin-bottom:3px',\n"
    "      'word-break:break-all',\n"
    "    ].join(';');\n"
    "    var safeText = String(text)\n"
    "      .replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')\n"
    "      .replace(/\\n/g,'<br>');\n"
    "    var extraHtml = extra\n"
    "      ? '<div style=\"color:#8ea3b0;margin-top:2px;font-size:11px;\">' +\n"
    "          String(extra).replace(/</g,'&lt;').replace(/\\n/g,'<br>') + '</div>'\n"
    "      : '';\n"
    "    entry.innerHTML =\n"
    "      '<span style=\"color:#2a4a38;font-size:10px;\">[' + ts + ']</span> ' +\n"
    "      '<span style=\"color:' + s.color + ';\">' + s.icon + ' ' + safeText + '</span>' +\n"
    "      extraHtml;\n"
    "    TermLog._bodyEl.appendChild(entry);\n"
    "    /* Обмежуємо кількість записів */\n"
    "    while (TermLog._bodyEl.children.length > TermLog._maxEntries) {\n"
    "      TermLog._bodyEl.removeChild(TermLog._bodyEl.firstChild);\n"
    "    }\n"
    "    TermLog.scrollBottom();\n"
    "    /* Оновлюємо лічильник */\n"
    "    if (type === 'error' || type === 'warning') {\n"
    "      var cnt = document.getElementById('termlog-count');\n"
    "      if (cnt) {\n"
    "        cnt.style.display = 'inline';\n"
    "        cnt.textContent = parseInt(cnt.textContent||0) + 1;\n"
    "      }\n"
    "    }\n"
    "  },\n\n"

    "  scrollBottom: function() {\n"
    "    if (TermLog._bodyEl)\n"
    "      TermLog._bodyEl.scrollTop = TermLog._bodyEl.scrollHeight;\n"
    "  },\n\n"

    "  clear: function() {\n"
    "    if (TermLog._bodyEl) TermLog._bodyEl.innerHTML = '';\n"
    "    var cnt = document.getElementById('termlog-count');\n"
    "    if (cnt) { cnt.style.display='none'; cnt.textContent='0'; }\n"
    "  },\n\n"

    "  copyAll: function() {\n"
    "    if (!TermLog._bodyEl) return;\n"
    "    var text = TermLog._bodyEl.innerText || TermLog._bodyEl.textContent;\n"
    "    navigator.clipboard.writeText(text).then(function() {\n"
    "      TermLog.log('info', 'Лог скопійовано в буфер обміну');\n"
    "    });\n"
    "  },\n\n"

    "  /* ── Ручне виконання команди ── */\n"
    "  runManual: function() {\n"
    "    var inp = document.getElementById('termlog-cmd-input');\n"
    "    if (!inp || !inp.value.trim()) return;\n"
    "    var cmd = inp.value.trim();\n"
    "    inp.value = '';\n"
    "    /* Додаємо в історію */\n"
    "    TermLog._history = TermLog._history || [];\n"
    "    TermLog._history.push(cmd);\n"
    "    TermLog._histIdx = TermLog._history.length;\n"
    "    /* Виконуємо */\n"
    "    TermLog.execCmd(cmd);\n"
    "  },\n\n"

    "  /* ── Виконати команду через sshCall ── */\n"
    "  execCmd: function(cmd) {\n"
    "    var r = window.getActiveRouter ? window.getActiveRouter() : null;\n"
    "    if (!r) {\n"
    "      TermLog.log('error', 'Немає підключеного роутера');\n"
    "      return;\n"
    "    }\n"
    "    TermLog.log('cmd', cmd);\n"
    "    TermLog.show();\n"
    "    if (window.sshCall) {\n"
    "      window.sshCall(r, cmd)\n"
    "        .then(function(d) {\n"
    "          var out = typeof d === 'string' ? d\n"
    "                  : (d && d.output) ? d.output\n"
    "                  : (d && d.text)   ? d.text\n"
    "                  : (d && d.result) ? d.result\n"
    "                  : (d && d.error)  ? d.error\n"
    "                  : JSON.stringify(d);\n"
    "          TermLog.log('ok', out || '(OK — порожня відповідь)');\n"
    "        })\n"
    "        .catch(function(e) {\n"
    "          TermLog.log('error', String(e));\n"
    "        });\n"
    "    } else {\n"
    "      TermLog.log('error', 'sshCall недоступний');\n"
    "    }\n"
    "  },\n\n"

    "  /* ── Читати останній export з роутера ── */\n"
    "  readExport: function() {\n"
    "    var r = window.getActiveRouter ? window.getActiveRouter() : null;\n"
    "    if (!r) { TermLog.log('error', 'Немає роутера'); return; }\n"
    "    TermLog.log('info', 'Читаємо router_config.rsc з роутера...');\n"
    "    TermLog.show();\n"
    "    /* Спочатку export compact, потім читаємо */\n"
    "    var cmds = [\n"
    "      '/export compact file=router_config',\n"
    "      ':delay 2s',\n"
    "      '/file print where name~\".rsc\"',\n"
    "    ];\n"
    "    if (window.sshCall) {\n"
    "      window.sshCall(r, '/export compact')\n"
    "        .then(function(d) {\n"
    "          var out = typeof d === 'string' ? d\n"
    "                  : (d && (d.output||d.text||d.result)) || '';\n"
    "          if (out && out.length > 50) {\n"
    "            TermLog.log('ok', '=== EXPORT (рядків: ' + out.split('\\n').length + ') ===');\n"
    "            /* Показуємо повний текст */\n"
    "            var full = document.createElement('div');\n"
    "            full.style.cssText = 'background:#050d08;border:1px solid #1a3a2a;border-radius:6px;' +\n"
    "              'padding:8px 12px;margin:4px 0;max-height:200px;overflow-y:auto;' +\n"
    "              'font-family:monospace;font-size:11px;color:#8ea3b0;white-space:pre;';\n"
    "            full.textContent = out;\n"
    "            TermLog._bodyEl.appendChild(full);\n"
    "            /* Кнопка скопіювати */\n"
    "            var copyBtn = document.createElement('button');\n"
    "            copyBtn.textContent = '📋 Копіювати export';\n"
    "            copyBtn.style.cssText = 'background:#1a2a3a;border:1px solid #2a3a5a;' +\n"
    "              'color:#5b9bd5;border-radius:5px;padding:3px 10px;cursor:pointer;' +\n"
    "              'font-size:11px;margin:4px 0;';\n"
    "            copyBtn.onclick = function() {\n"
    "              navigator.clipboard.writeText(out);\n"
    "              copyBtn.textContent = '✅ Скопійовано!';\n"
    "              setTimeout(function(){copyBtn.textContent='📋 Копіювати export';},2000);\n"
    "            };\n"
    "            TermLog._bodyEl.appendChild(copyBtn);\n"
    "            /* Кнопка відкрити в Diff */\n"
    "            var diffBtn = document.createElement('button');\n"
    "            diffBtn.textContent = '🔄 Відкрити в Diff';\n"
    "            diffBtn.style.cssText = 'background:#1a3a2a;border:1px solid #2a5a3a;' +\n"
    "              'color:#5fd0a5;border-radius:5px;padding:3px 10px;cursor:pointer;' +\n"
    "              'font-size:11px;margin:4px 4px;';\n"
    "            diffBtn.onclick = function() {\n"
    "              var ta = document.getElementById('da-text-a');\n"
    "              if (ta) { ta.value = out; }\n"
    "              TermLog.log('info', 'Export відкрито в Diff Конфіг A');\n"
    "            };\n"
    "            TermLog._bodyEl.appendChild(diffBtn);\n"
    "            TermLog.scrollBottom();\n"
    "          } else {\n"
    "            TermLog.log('warning', 'Export порожній або занадто короткий: ' + out);\n"
    "          }\n"
    "        })\n"
    "        .catch(function(e) {\n"
    "          TermLog.log('error', 'Export failed: ' + e);\n"
    "        });\n"
    "    }\n"
    "  },\n\n"

    "  /* ── Перехоплення sshCall ── */\n"
    "  interceptSSH: function() {\n"
    "    var _orig = window.sshCall;\n"
    "    if (!_orig || window.sshCall._intercepted) return;\n"
    "    window.sshCall = function(router, cmd) {\n"
    "      /* Логуємо команду */\n"
    "      var routerName = router ? (router.ip||router.host||'?') : '?';\n"
    "      TermLog.log('cmd', '[' + routerName + '] ' + cmd);\n"
    "      /* Виконуємо оригінал */\n"
    "      return _orig(router, cmd)\n"
    "        .then(function(d) {\n"
    "          var out = typeof d === 'string' ? d\n"
    "                  : (d && d.output) ? d.output\n"
    "                  : (d && d.text)   ? d.text\n"
    "                  : (d && d.result) ? d.result\n"
    "                  : (d && d.error)  ? ('ERROR: ' + d.error)\n"
    "                  : JSON.stringify(d);\n"
    "          var type = (d && d.error) ? 'error' : 'ok';\n"
    "          TermLog.log(type, out || '(OK)');\n"
    "          return d;\n"
    "        })\n"
    "        .catch(function(e) {\n"
    "          TermLog.log('error', String(e));\n"
    "          throw e;\n"
    "        });\n"
    "    };\n"
    "    window.sshCall._intercepted = true;\n"
    "    console.log('[TermLog] sshCall intercepted ✅');\n"
    "  },\n\n"

    "  /* ── Перехоплення restCall ── */\n"
    "  interceptREST: function() {\n"
    "    var _orig = window.restCall;\n"
    "    if (!_orig || window.restCall._intercepted) return;\n"
    "    window.restCall = function(router, method, path, body) {\n"
    "      var routerName = router ? (router.ip||router.host||'?') : '?';\n"
    "      TermLog.log('info', '[REST ' + routerName + '] ' + method + ' ' + path);\n"
    "      return _orig(router, method, path, body)\n"
    "        .then(function(d) {\n"
    "          if (d && d.error) TermLog.log('error', 'REST error: ' + d.error);\n"
    "          return d;\n"
    "        })\n"
    "        .catch(function(e) {\n"
    "          TermLog.log('error', 'REST failed: ' + e);\n"
    "          throw e;\n"
    "        });\n"
    "    };\n"
    "    window.restCall._intercepted = true;\n"
    "    console.log('[TermLog] restCall intercepted ✅');\n"
    "  },\n"
    "};\n\n"

    "/* ── Запуск ── */\n"
    "document.addEventListener('DOMContentLoaded', function() {\n"
    "  setTimeout(function() {\n"
    "    TermLog.init();\n"
    "    /* Перехоплюємо після завантаження всіх скриптів */\n"
    "    setTimeout(function() {\n"
    "      TermLog.interceptSSH();\n"
    "      TermLog.interceptREST();\n"
    "      TermLog.log('info', 'Terminal Log готовий. Всі SSH/REST команди будуть відображатись тут.');\n"
    "    }, 1500);\n"
    "  }, 500);\n"
    "});\n\n"
    "console.log('[TermLog] Loaded ✅');\n"
)

with open('ai-agent/terminal-log.js', 'w', encoding='utf-8') as f:
    f.write(TERMINAL_JS)

r = subprocess.run(['node','--check','ai-agent/terminal-log.js'],
                   capture_output=True, text=True)
print('terminal-log.js:', 'OK ✅' if r.returncode==0 else '❌\n'+r.stderr[:200])

# ════════════════════════════════════
# 2. Підключаємо в index.html — ОСТАННІМ
# ════════════════════════════════════
with open('index.html', 'r', encoding='utf-8') as f:
    html = f.read()

if 'terminal-log.js' not in html:
    # Додаємо перед </body>
    html = html.replace(
        '</body>',
        '  <script src="ai-agent/terminal-log.js"></script>\n</body>'
    )
    with open('index.html', 'w', encoding='utf-8') as f:
        f.write(html)
    print('OK: terminal-log.js в index.html ✅')
else:
    print('OK: terminal-log.js вже є ✅')

# ════════════════════════════════════
# 3. Виправляємо renderDiffVisual
# ════════════════════════════════════
with open('diff-apply.js', 'r', encoding='utf-8') as f:
    diff = f.read()

idx = diff.find('renderDiffVisual')
depth = 0; found = False; end = idx
for i, ch in enumerate(diff[idx:], idx):
    if ch == '{': depth += 1; found = True
    elif ch == '}': depth -= 1
    if found and depth == 0: end = i + 1; break

NEW_RENDER = (
    "renderDiffVisual(textA, textB, diff, outputEl, statsEl) {\n"
    "  if (!outputEl) return;\n"
    "  var pairs   = diff.pairs   || [];\n"
    "  var added   = diff.added   || [];\n"
    "  var removed = diff.removed || [];\n\n"
    "  /* ── Статистика ── */\n"
    "  var nAdded   = added.length;\n"
    "  var nRemoved = removed.length;\n"
    "  var nChanged = pairs.filter(function(p){return p.type==='change';}).length;\n"
    "  var nSame    = pairs.filter(function(p){return p.type==='equal'; }).length;\n\n"
    "  if (statsEl) {\n"
    "    statsEl.innerHTML =\n"
    "      '<div style=\"display:flex;gap:8px;flex-wrap:wrap;margin-bottom:8px;\">'+\n"
    "      '<span style=\"background:#0a2a0a;border:1px solid #2a5a2a;border-radius:5px;' +\n"
    "        'padding:2px 10px;color:#5fd0a5;font-size:12px;\">+' + nAdded + ' додано</span>'+\n"
    "      '<span style=\"background:#2a0a0a;border:1px solid #5a2a2a;border-radius:5px;' +\n"
    "        'padding:2px 10px;color:#e08080;font-size:12px;\">−' + nRemoved + ' видалено</span>'+\n"
    "      '<span style=\"background:#1a1a0a;border:1px solid #4a4a2a;border-radius:5px;' +\n"
    "        'padding:2px 10px;color:#f0c060;font-size:12px;\">~ ' + nChanged + ' змінено</span>'+\n"
    "      '<span style=\"background:#0a0f1a;border:1px solid #2a3a4a;border-radius:5px;' +\n"
    "        'padding:2px 10px;color:#4a6070;font-size:12px;\">' + nSame + ' однаково</span>'+\n"
    "      '</div>';\n"
    "  }\n\n"
    "  /* ── Заголовки колонок ── */\n"
    "  var html = '<table style=\"width:100%;border-collapse:collapse;table-layout:fixed;\">'+\n"
    "    '<colgroup><col style=\"width:50%\"><col style=\"width:50%\"></colgroup>'+\n"
    "    '<thead><tr>'+\n"
    "    '<th style=\"background:#0a1a0a;color:#5fd0a5;padding:8px 12px;' +\n"
    "      'border:1px solid #1a3a2a;font-size:12px;text-align:left;\">'+\n"
    "    '📄 КОНФІГ A — Поточний (на роутері)</th>'+\n"
    "    '<th style=\"background:#0a0f1a;color:#5b9bd5;padding:8px 12px;' +\n"
    "      'border:1px solid #1a2a3a;font-size:12px;text-align:left;\">'+\n"
    "    '📝 КОНФІГ B — Новий (для застосування)</th>'+\n"
    "    '</tr></thead><tbody>';\n\n"
    "  /* ── Рядки ── */\n"
    "  pairs.forEach(function(pair) {\n"
    "    var cellStyle = 'padding:3px 10px;font-family:monospace;font-size:11px;' +\n"
    "      'border:1px solid #1a2a30;vertical-align:top;white-space:pre-wrap;word-break:break-word;';\n\n"
    "    if (pair.type === 'equal') {\n"
    "      /* Однакові рядки — сіре */\n"
    "      var lineStyle = cellStyle + 'color:#3a5060;background:#070d10;';\n"
    "      html += '<tr>'+\n"
    "        '<td style=\"' + lineStyle + '\">' + escHtml(pair.lineA || '') + '</td>'+\n"
    "        '<td style=\"' + lineStyle + '\">' + escHtml(pair.lineB || '') + '</td>'+\n"
    "        '</tr>';\n\n"
    "    } else if (pair.type === 'remove') {\n"
    "      /* Тільки в A — червоне */\n"
    "      html += '<tr>'+\n"
    "        '<td style=\"' + cellStyle + 'background:#1a0505;color:#e08080;border-left:3px solid #c03030;\">'+\n"
    "          '<span style=\"color:#c03030;font-size:10px;margin-right:4px;\">−</span>' +\n"
    "          escHtml(pair.lineA || '') +\n"
    "          '<div style=\"color:#4a2020;font-size:10px;margin-top:2px;\">'+\n"
    "          '⚠ Тільки в A — буде ВИДАЛЕНО при застосуванні B</div>'+\n"
    "        '</td>'+\n"
    "        '<td style=\"' + cellStyle + 'background:#0d0505;color:#3a1515;\">'+\n"
    "          '<span style=\"color:#3a1515;\">— відсутнє в B —</span>'+\n"
    "        '</td>'+\n"
    "        '</tr>';\n\n"
    "    } else if (pair.type === 'add') {\n"
    "      /* Тільки в B — зелене */\n"
    "      html += '<tr>'+\n"
    "        '<td style=\"' + cellStyle + 'background:#050d05;color:#2a4a2a;\">'+\n"
    "          '<span style=\"color:#2a4a2a;\">— відсутнє в A —</span>'+\n"
    "        '</td>'+\n"
    "        '<td style=\"' + cellStyle + 'background:#051505;color:#5fd0a5;border-left:3px solid #3a9a3a;\">'+\n"
    "          '<span style=\"color:#3a9a3a;font-size:10px;margin-right:4px;\">+</span>' +\n"
    "          escHtml(pair.lineB || '') +\n"
    "          '<div style=\"color:#2a5a2a;font-size:10px;margin-top:2px;\">'+\n"
    "          '✅ Тільки в B — буде ДОДАНО при застосуванні</div>'+\n"
    "        '</td>'+\n"
    "        '</tr>';\n\n"
    "    } else if (pair.type === 'change') {\n"
    "      /* Змінено — жовте */\n"
    "      html += '<tr>'+\n"
    "        '<td style=\"' + cellStyle + 'background:#1a1200;color:#d4a820;border-left:3px solid #a07820;\">'+\n"
    "          '<span style=\"color:#a07820;font-size:10px;margin-right:4px;\">~</span>' +\n"
    "          escHtml(pair.lineA || '') +\n"
    "          '<div style=\"color:#504010;font-size:10px;margin-top:2px;\">'+\n"
    "          '~ Змінено в A</div>'+\n"
    "        '</td>'+\n"
    "        '<td style=\"' + cellStyle + 'background:#0d1800;color:#b8d060;border-left:3px solid #608030;\">'+\n"
    "          '<span style=\"color:#608030;font-size:10px;margin-right:4px;\">~</span>' +\n"
    "          escHtml(pair.lineB || '') +\n"
    "          '<div style=\"color:#304010;font-size:10px;margin-top:2px;\">'+\n"
    "          '~ Нове значення в B</div>'+\n"
    "        '</td>'+\n"
    "        '</tr>';\n"
    "    }\n"
    "  });\n\n"
    "  html += '</tbody></table>';\n\n"
    "  function escHtml(s) {\n"
    "    return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');\n"
    "  }\n\n"
    "  outputEl.innerHTML = html;\n\n"
    "  /* AI кнопка */\n"
    "  var aiDiv = document.getElementById('da-ai-explain');\n"
    "  if (!aiDiv) {\n"
    "    aiDiv = document.createElement('div');\n"
    "    aiDiv.id = 'da-ai-explain';\n"
    "    outputEl.parentNode.appendChild(aiDiv);\n"
    "  }\n"
    "  aiDiv.innerHTML = '';\n"
    "  var aiBtn = document.createElement('button');\n"
    "  aiBtn.textContent = '🤖 AI — Пояснити відмінності';\n"
    "  aiBtn.style.cssText = 'margin-top:12px;background:linear-gradient(135deg,#1a3a2a,#2a5a3a);' +\n"
    "    'border:1px solid #3a7a4a;color:#5fd0a5;border-radius:8px;padding:8px 18px;' +\n"
    "    'cursor:pointer;font-size:13px;font-weight:600;';\n"
    "  aiBtn.onclick = function() { window.DiffAIExplain && DiffAIExplain(textA, textB); };\n"
    "  aiDiv.appendChild(aiBtn);\n"
    "}"
)

diff = diff[:idx] + NEW_RENDER + diff[end:]

with open('diff-apply.js', 'w', encoding='utf-8') as f:
    f.write(diff)

r2 = subprocess.run(['node','--check','diff-apply.js'],
                    capture_output=True, text=True)
print('diff-apply:', 'OK ✅' if r2.returncode==0 else '❌\n'+r2.stderr[:200])

print('\nВсе готово! npm start')