# -*- coding: utf-8 -*-
import subprocess

with open('ai-agent/terminal-log.js', 'r', encoding='utf-8') as f:
    tl = f.read()

# ── 1. Фікс фільтру роутерів ──
old_filter = (
    "        /* Фільтруємо — тільки справжні роутери (мають user+pass+sshPort) */\n"
    "        routers = rs.filter(function(r) {\n"
    "          return r.ip && r.user && r.pass !== undefined &&\n"
    "                 r.id && r.id.startsWith('r_');\n"
    "        });\n"
    "        /* Прибираємо дублікати по IP */\n"
    "        var seen = {};\n"
    "        routers = routers.filter(function(r) {\n"
    "          if (seen[r.ip]) return false;\n"
    "          seen[r.ip] = true;\n"
    "          return true;\n"
    "        });"
)
new_filter = (
    "        /* Фільтруємо — тільки справжні роутери */\n"
    "        routers = rs.filter(function(r) {\n"
    "          /* Роутер має: ip, user, pass, і або sshPort або port */\n"
    "          return r.ip && r.user &&\n"
    "                 r.pass !== undefined && r.pass !== null &&\n"
    "                 (r.sshPort || r.port || r.id);\n"
    "        });\n"
    "        /* Прибираємо дублікати по IP */\n"
    "        var seen = {};\n"
    "        routers = routers.filter(function(r) {\n"
    "          if (seen[r.ip]) return false;\n"
    "          seen[r.ip] = true;\n"
    "          return true;\n"
    "        });"
)
if old_filter in tl:
    tl = tl.replace(old_filter, new_filter)
    print('OK: фільтр роутерів виправлено ✅')

# ── 2. Замінюємо showMultiRouter — додаємо групи ──
old_panel_html = (
    "    var checkboxes = routers.map(function(r) {\n"
    "      return '<label style=\"display:flex;align-items:center;gap:8px;padding:4px 0;'+\n"
    "        'color:#c9d8e4;font-size:12px;cursor:pointer;\">'+\n"
    "        '<input type=\"checkbox\" class=\"mr-check\" data-id=\"' + r.id + '\" checked '+\n"
    "          'style=\"accent-color:#5fd0a5;\">'+\n"
    "        '<span style=\"color:#5fd0a5;\">◉</span> '+\n"
    "        r.name + ' <span style=\"color:#4a6070;\">' + r.ip + '</span>'+\n"
    "        '</label>';\n"
    "    }).join('');\n"
    "    panel.innerHTML =\n"
    "      '<div style=\"color:#90c060;font-weight:700;margin-bottom:10px;\">🔀 Multi-Router виконання</div>'+\n"
    "      checkboxes +"
)

new_panel_html = (
    "    /* Завантажуємо групи */\n"
    "    var groups = {};\n"
    "    try {\n"
    "      groups = JSON.parse(localStorage.getItem('mr-groups') || '{}');\n"
    "    } catch(e) {}\n\n"
    "    var checkboxes = routers.map(function(r) {\n"
    "      return '<label style=\"display:flex;align-items:center;gap:8px;padding:4px 0;'+\n"
    "        'color:#c9d8e4;font-size:12px;cursor:pointer;\">'+\n"
    "        '<input type=\"checkbox\" class=\"mr-check\" data-id=\"' + r.id + '\" data-ip=\"' + r.ip + '\" checked '+\n"
    "          'style=\"accent-color:#5fd0a5;\">'+\n"
    "        '<span style=\"color:#5fd0a5;\">◉</span> '+\n"
    "        (r.name||r.ip) + ' <span style=\"color:#4a6070;\">' + r.ip + '</span>'+\n"
    "        '</label>';\n"
    "    }).join('');\n\n"
    "    /* Кнопки збережених груп */\n"
    "    var groupBtns = Object.keys(groups).map(function(gname) {\n"
    "      var gids = groups[gname];\n"
    "      return '<button class=\"mr-group-btn\" data-group=\"' + gname + '\" '+\n"
    "        'style=\"background:#1a1a2a;border:1px solid #3a2a5a;color:#c084fc;'+\n"
    "        'border-radius:5px;padding:2px 8px;cursor:pointer;font-size:11px;\">'+\n"
    "        '📁 ' + gname + ' (' + gids.length + ')'+\n"
    "        '</button>';\n"
    "    }).join(' ');\n\n"
    "    panel.innerHTML =\n"
    "      '<div style=\"color:#90c060;font-weight:700;margin-bottom:8px;\">🔀 Multi-Router виконання</div>'+\n"
    "      /* Рядок груп */\n"
    "      (Object.keys(groups).length > 0\n"
    "        ? '<div style=\"margin-bottom:8px;display:flex;flex-wrap:wrap;gap:4px;\">'+\n"
    "            '<span style=\"color:#4a6070;font-size:11px;margin-right:4px;\">Групи:</span>'+\n"
    "            groupBtns+\n"
    "          '</div>'\n"
    "        : '') +\n"
    "      /* Список роутерів */\n"
    "      '<div id=\"mr-router-list\" style=\"max-height:200px;overflow-y:auto;margin-bottom:8px;\">'+\n"
    "        checkboxes+\n"
    "      '</div>'+\n"
    "      /* Кнопки дій */\n"
    "      '<div style=\"display:flex;gap:4px;flex-wrap:wrap;margin-bottom:8px;\">'+\n"
    "        '<button id=\"mr-select-all\" style=\"background:transparent;border:1px solid #2a3b48;'+\n"
    "          'color:#4a6070;border-radius:5px;padding:2px 8px;cursor:pointer;font-size:11px;\">✓ Всі</button>'+\n"
    "        '<button id=\"mr-select-none\" style=\"background:transparent;border:1px solid #2a3b48;'+\n"
    "          'color:#4a6070;border-radius:5px;padding:2px 8px;cursor:pointer;font-size:11px;\">✗ Жодного</button>'+\n"
    "        '<button id=\"mr-save-group\" style=\"background:#1a1a2a;border:1px solid #3a2a5a;'+\n"
    "          'color:#c084fc;border-radius:5px;padding:2px 8px;cursor:pointer;font-size:11px;\">💾 Зберегти групу</button>'+\n"
    "      '</div>'+\n"
    "      '<div style=\"margin-top:4px;display:flex;gap:8px;\">'+\n"
    "        '<button id=\"mr-run-all\" style=\"background:#1a3a1a;border:1px solid #3a6a2a;'+\n"
    "          'color:#90c060;border-radius:6px;padding:5px 14px;cursor:pointer;font-size:12px;flex:1;\">'+\n"
    "          '▶ Виконати на вибраних</button>'+\n"
    "        '<button id=\"mr-cancel\" style=\"background:transparent;border:1px solid #2a3b48;'+\n"
    "          'color:#4a6070;border-radius:6px;padding:5px 10px;cursor:pointer;font-size:12px;\">✕</button>'+\n"
    "      '</div>';\n"
    "    var bar = document.getElementById('termlog-input-bar');\n"
    "    if (bar) {\n"
    "      bar.style.position = 'relative';\n"
    "      bar.appendChild(panel);\n"
    "    }\n\n"
    "    /* Хелпер — отримати вибрані ID */\n"
    "    function getCheckedIds() {\n"
    "      return Array.from(panel.querySelectorAll('.mr-check:checked'))\n"
    "        .map(function(c) { return c.dataset.id; });\n"
    "    }\n\n"
    "    /* Вибрати всі */\n"
    "    document.getElementById('mr-select-all').onclick = function() {\n"
    "      panel.querySelectorAll('.mr-check').forEach(function(c) { c.checked = true; });\n"
    "    };\n"
    "    /* Зняти всі */\n"
    "    document.getElementById('mr-select-none').onclick = function() {\n"
    "      panel.querySelectorAll('.mr-check').forEach(function(c) { c.checked = false; });\n"
    "    };\n"
    "    /* Зберегти групу */\n"
    "    document.getElementById('mr-save-group').onclick = function() {\n"
    "      var ids = getCheckedIds();\n"
    "      if (ids.length === 0) {\n"
    "        TermLog.log('warning', 'Виберіть роутери для групи');\n"
    "        return;\n"
    "      }\n"
    "      var gname = prompt('Назва групи (наприклад: Офіси, Склади):');\n"
    "      if (!gname || !gname.trim()) return;\n"
    "      gname = gname.trim();\n"
    "      try {\n"
    "        var gs = JSON.parse(localStorage.getItem('mr-groups') || '{}');\n"
    "        gs[gname] = ids;\n"
    "        localStorage.setItem('mr-groups', JSON.stringify(gs));\n"
    "        TermLog.log('ok', '💾 Групу \"' + gname + '\" збережено (' + ids.length + ' роутерів)');\n"
    "        /* Перезавантажуємо панель */\n"
    "        panel.remove();\n"
    "        setTimeout(function() { TermLog.showMultiRouter(); }, 100);\n"
    "      } catch(e) { TermLog.log('error', 'Помилка збереження групи: ' + e); }\n"
    "    };\n"
    "    /* Кнопки груп — вибирають роутери групи */\n"
    "    panel.querySelectorAll('.mr-group-btn').forEach(function(btn) {\n"
    "      btn.addEventListener('click', function() {\n"
    "        var gname = this.dataset.group;\n"
    "        var gs = JSON.parse(localStorage.getItem('mr-groups') || '{}');\n"
    "        var gids = gs[gname] || [];\n"
    "        /* Спочатку знімаємо всі */\n"
    "        panel.querySelectorAll('.mr-check').forEach(function(c) { c.checked = false; });\n"
    "        /* Вибираємо тільки з групи */\n"
    "        panel.querySelectorAll('.mr-check').forEach(function(c) {\n"
    "          if (gids.indexOf(c.dataset.id) >= 0) c.checked = true;\n"
    "        });\n"
    "        /* Підсвічуємо активну групу */\n"
    "        panel.querySelectorAll('.mr-group-btn').forEach(function(b) {\n"
    "          b.style.background = '#1a1a2a';\n"
    "          b.style.color = '#c084fc';\n"
    "        });\n"
    "        this.style.background = '#3a1a5a';\n"
    "        this.style.color = '#e0a0ff';\n"
    "        TermLog.log('info', '📁 Група \"' + gname + '\": вибрано ' + gids.length + ' роутерів');\n"
    "      });\n"
    "      /* Правий клік — видалити групу */\n"
    "      btn.addEventListener('contextmenu', function(e) {\n"
    "        e.preventDefault();\n"
    "        var gname = this.dataset.group;\n"
    "        if (confirm('Видалити групу \"' + gname + '\"?')) {\n"
    "          var gs = JSON.parse(localStorage.getItem('mr-groups') || '{}');\n"
    "          delete gs[gname];\n"
    "          localStorage.setItem('mr-groups', JSON.stringify(gs));\n"
    "          panel.remove();\n"
    "          setTimeout(function() { TermLog.showMultiRouter(); }, 100);\n"
    "          TermLog.log('info', '🗑 Групу \"' + gname + '\" видалено');\n"
    "        }\n"
    "      });\n"
    "    });\n"
    "    document.getElementById('mr-cancel').onclick = function() { panel.remove(); };\n"
    "    document.getElementById('mr-run-all').onclick = function() {\n"
    "      var cmd = document.getElementById('termlog-cmd-input').value.trim();\n"
    "      if (!cmd) { TermLog.log('error', 'Введіть команду в поле вводу'); return; }\n"
    "      var ids = getCheckedIds();\n"
    "      var selected = routers.filter(function(r) { return ids.indexOf(r.id) >= 0; });\n"
    "      panel.remove();\n"
    "      TermLog.runOnMultiple(cmd, selected);\n"
    "    };\n\n"
    "    panel.innerHTML =\n"
    "      '<div style=\"color:#90c060;font-weight:700;margin-bottom:10px;\">🔀 Multi-Router виконання</div>'+\n"
    "      checkboxes +"
)

if old_panel_html in tl:
    tl = tl.replace(old_panel_html, new_panel_html)
    print('OK: панель з групами ✅')
else:
    print('WARN: панель не знайдено')
    idx = tl.find('var checkboxes = routers.map')
    print(repr(tl[max(0,idx-50):idx+200]))

with open('ai-agent/terminal-log.js', 'w', encoding='utf-8') as f:
    f.write(tl)

r = subprocess.run(['node','--check','ai-agent/terminal-log.js'],
                   capture_output=True, text=True)
print('terminal-log:', 'OK ✅' if r.returncode==0 else '❌\n'+r.stderr[:200])
print('\nВсе готово! npm start')