# -*- coding: utf-8 -*-
import subprocess

with open('ai-agent/terminal-log.js', 'r', encoding='utf-8') as f:
    tl = f.read()

# ── Знаходимо input bar і замінюємо на highlighting версію ──
old_input = (
    "      '<div id=\"termlog-input-bar\" style=\"display:flex;gap:8px;padding:6px 14px;' +\n"
    "        'border-top:1px solid #1a2a38;background:#0a1218;flex-shrink:0;\">'+\n"
    "        '<span style=\"color:#5fd0a5;\">❯</span>'+\n"
    "        '<input id=\"termlog-cmd-input\" type=\"text\" placeholder=\"Виконати команду на роутері...\" '+\n"
    "          'style=\"flex:1;background:transparent;border:none;outline:none;' +\n"
    "          'color:#e6edf3;font-family:monospace;font-size:12px;\">'+\n"
    "        '<button id=\"termlog-run\" style=\"background:#1a3a2a;border:1px solid #2a5a3a;' +\n"
    "          'color:#5fd0a5;border-radius:5px;padding:2px 12px;cursor:pointer;font-size:11px;\">▶ Run</button>'+\n"
    "        '<button id=\"termlog-export-read\" style=\"background:#1a2a3a;border:1px solid #2a3a5a;' +\n"
    "          'color:#5b9bd5;border-radius:5px;padding:2px 12px;cursor:pointer;font-size:11px;\">📄 Читати export</button>'+\n"
    "      '</div>'"
)

new_input = (
    "      '<div id=\"termlog-input-bar\" style=\"display:flex;gap:8px;padding:6px 14px;' +\n"
    "        'border-top:1px solid #1a2a38;background:#0a1218;flex-shrink:0;position:relative;\">'+\n"
    "        '<span style=\"color:#5fd0a5;font-family:monospace;font-size:13px;\">❯</span>'+\n"
    "        '<div style=\"flex:1;position:relative;\">'+\n"
    "          /* Шар підсвітки — під текстом */\n"
    "          '<div id=\"termlog-highlight\" style=\"position:absolute;top:0;left:0;right:0;bottom:0;' +\n"
    "            'font-family:monospace;font-size:12px;line-height:1.5;pointer-events:none;' +\n"
    "            'white-space:pre;overflow:hidden;padding:0;\"></div>'+\n"
    "          /* Прозорий input поверх */\n"
    "          '<input id=\"termlog-cmd-input\" type=\"text\" '+\n"
    "            'placeholder=\"Команда... (Tab = autocomplete, ↑↓ = історія)\" '+\n"
    "            'style=\"width:100%;background:transparent;border:none;outline:none;' +\n"
    "            'color:#e6edf3;font-family:monospace;font-size:12px;position:relative;' +\n"
    "            'z-index:1;caret-color:#5fd0a5;\">'+\n"
    "          /* Inline autocomplete hint */\n"
    "          '<div id=\"termlog-hint\" style=\"position:absolute;top:0;left:0;right:0;' +\n"
    "            'font-family:monospace;font-size:12px;pointer-events:none;' +\n"
    "            'color:#2a4a38;white-space:pre;overflow:hidden;\"></div>'+\n"
    "        '</div>'+\n"
    "        '<button id=\"termlog-run\" style=\"background:#1a3a2a;border:1px solid #2a5a3a;' +\n"
    "          'color:#5fd0a5;border-radius:5px;padding:2px 12px;cursor:pointer;font-size:11px;\">▶ Run</button>'+\n"
    "        '<button id=\"termlog-export-read\" style=\"background:#1a2a3a;border:1px solid #2a3a5a;' +\n"
    "          'color:#5b9bd5;border-radius:5px;padding:2px 12px;cursor:pointer;font-size:11px;\">📄 Export</button>'+\n"
    "      '</div>'"
)

if old_input in tl:
    tl = tl.replace(old_input, new_input)
    print('OK: input bar з підсвіткою ✅')
else:
    print('WARN: input bar не знайдено точно')

# ── Знаходимо де вішається keydown listener і додаємо Tab + highlighting ──
old_keydown = (
    "    /* Enter в input */\n"
    "    document.getElementById('termlog-cmd-input').addEventListener('keydown', function(e) {\n"
    "      if (e.key === 'Enter') TermLog.runManual();\n"
    "      /* Стрілки — історія команд */\n"
    "      if (e.key === 'ArrowUp') {\n"
    "        TermLog._histIdx = Math.max(0, (TermLog._histIdx || 0) - 1);\n"
    "        this.value = TermLog._history[TermLog._histIdx] || '';\n"
    "        e.preventDefault();\n"
    "      }\n"
    "      if (e.key === 'ArrowDown') {\n"
    "        TermLog._histIdx = Math.min((TermLog._history||[]).length,\n"
    "          (TermLog._histIdx || 0) + 1);\n"
    "        this.value = TermLog._history[TermLog._histIdx] || '';\n"
    "        e.preventDefault();\n"
    "      }\n"
    "    });"
)

new_keydown = (
    "    /* ── Enter/Tab/Arrow listeners ── */\n"
    "    var cmdInput = document.getElementById('termlog-cmd-input');\n"
    "    cmdInput.addEventListener('keydown', function(e) {\n"
    "      if (e.key === 'Enter') {\n"
    "        TermLog.runManual();\n"
    "        document.getElementById('termlog-hint').textContent = '';\n"
    "        document.getElementById('termlog-highlight').innerHTML = '';\n"
    "        return;\n"
    "      }\n"
    "      /* Tab — приймаємо autocomplete */\n"
    "      if (e.key === 'Tab') {\n"
    "        e.preventDefault();\n"
    "        var hint = TermLog._currentHint || '';\n"
    "        if (hint && hint.startsWith(this.value)) {\n"
    "          this.value = hint;\n"
    "          TermLog._currentHint = '';\n"
    "          document.getElementById('termlog-hint').textContent = '';\n"
    "          TermLog.updateHighlight(this.value);\n"
    "        } else {\n"
    "          /* Якщо hint не повний — доповнюємо до наступного пробілу */\n"
    "          var next = TermLog.getNextCompletion(this.value);\n"
    "          if (next) { this.value = next; TermLog.updateHighlight(next); }\n"
    "        }\n"
    "        return;\n"
    "      }\n"
    "      /* Стрілки — історія */\n"
    "      if (e.key === 'ArrowUp') {\n"
    "        e.preventDefault();\n"
    "        TermLog._histIdx = Math.max(0, (TermLog._histIdx || 0) - 1);\n"
    "        this.value = (TermLog._history || [])[TermLog._histIdx] || '';\n"
    "        TermLog.updateHighlight(this.value);\n"
    "        TermLog.updateHint(this.value);\n"
    "      }\n"
    "      if (e.key === 'ArrowDown') {\n"
    "        e.preventDefault();\n"
    "        TermLog._histIdx = Math.min(\n"
    "          (TermLog._history||[]).length,\n"
    "          (TermLog._histIdx||0) + 1);\n"
    "        this.value = (TermLog._history||[])[TermLog._histIdx] || '';\n"
    "        TermLog.updateHighlight(this.value);\n"
    "        TermLog.updateHint(this.value);\n"
    "      }\n"
    "    });\n"
    "    /* Input — оновлюємо підсвітку і hint в реальному часі */\n"
    "    cmdInput.addEventListener('input', function() {\n"
    "      TermLog.updateHighlight(this.value);\n"
    "      TermLog.updateHint(this.value);\n"
    "    });"
)

if old_keydown in tl:
    tl = tl.replace(old_keydown, new_keydown)
    print('OK: Tab + highlight listeners ✅')

# ── Додаємо методи підсвітки і autocomplete перед останньою дужкою ──
old_intercept = "  /* ── Перехоплення sshCall ── */"
new_methods = (
    "  /* ── База команд RouterOS для autocomplete ── */\n"
    "  _rosCommands: [\n"
    "    /* Головні меню */\n"
    "    '/ip address', '/ip route', '/ip firewall filter', '/ip firewall nat',\n"
    "    '/ip firewall mangle', '/ip firewall address-list',\n"
    "    '/ip dns', '/ip dhcp-server', '/ip dhcp-client',\n"
    "    '/ip service', '/ip neighbor', '/ip arp', '/ip pool',\n"
    "    '/interface ethernet', '/interface bridge', '/interface vlan',\n"
    "    '/interface wireless', '/interface wifi', '/interface wireguard',\n"
    "    '/interface list', '/interface monitor-traffic',\n"
    "    '/system identity', '/system resource', '/system clock',\n"
    "    '/system backup', '/system reboot', '/system shutdown',\n"
    "    '/system package', '/system scheduler', '/system script',\n"
    "    '/system logging', '/system health',\n"
    "    '/tool ping', '/tool traceroute', '/tool bandwidth-test',\n"
    "    '/tool torch', '/tool sniffer', '/tool netwatch',\n"
    "    '/tool profile', '/tool flood-ping',\n"
    "    '/routing ospf', '/routing bgp', '/routing filter',\n"
    "    '/caps-man', '/certificate', '/container',\n"
    "    '/export', '/export terse', '/export compact',\n"
    "    '/import', '/file print', '/file remove',\n"
    "    '/log print', '/ping', '/traceroute',\n"
    "    /* Дії */\n"
    "    '/ip address add', '/ip address remove', '/ip address print',\n"
    "    '/ip route add', '/ip route print',\n"
    "    '/ip firewall filter add', '/ip firewall filter print',\n"
    "    '/ip firewall filter remove', '/ip firewall filter disable',\n"
    "    '/ip firewall nat add', '/ip firewall nat print',\n"
    "    '/interface print', '/interface enable', '/interface disable',\n"
    "    '/ip dhcp-server lease print', '/ip arp print',\n"
    "    '/user print', '/user add', '/user set',\n"
    "    '/certificate add', '/certificate sign', '/certificate print',\n"
    "  ],\n\n"

    "  /* ── Словник параметрів по команді ── */\n"
    "  _rosParams: {\n"
    "    '/ip firewall filter add': 'chain= action= protocol= src-address= dst-address= in-interface= out-interface= comment=',\n"
    "    '/ip firewall nat add':    'chain= action= src-address= dst-address= to-addresses= to-ports= protocol= comment=',\n"
    "    '/ip address add':         'address= interface= comment=',\n"
    "    '/ip route add':           'dst-address= gateway= distance= comment=',\n"
    "    '/ip dns set':             'servers= allow-remote-requests=',\n"
    "    '/ip service set':         'port= address= disabled=',\n"
    "    '/interface bridge add':   'name= vlan-filtering= comment=',\n"
    "    '/user add':               'name= group= password= comment=',\n"
    "    '/tool ping':              'address= count= interval= size=',\n"
    "    '/tool torch':             'interface= src-address= dst-address= duration=',\n"
    "    '/ping':                   'address= count= interval= src-address=',\n"
    "  },\n\n"

    "  /* ── Токени підсвітки ── */\n"
    "  _tokenize: function(cmd) {\n"
    "    /* Розбиваємо команду на токени з кольорами */\n"
    "    var tokens = [];\n"
    "    var c = cmd || '';\n\n"
    "    /* 1. Шлях /ip/firewall/... */\n"
    "    var pathMatch = c.match(/^(\\/[a-z][a-z0-9\\-\\/]*)/);\n"
    "    if (pathMatch) {\n"
    "      tokens.push({ text: pathMatch[1], color: '#5b9bd5' }); /* синій */\n"
    "      c = c.slice(pathMatch[1].length);\n"
    "    }\n\n"
    "    /* 2. Дія (add/remove/set/print/enable/disable/...) */\n"
    "    var actionMatch = c.match(/^\\s*(add|remove|set|print|get|find|enable|disable|reset|export|import|monitor|move|copy|comment|unset|edit)\\b/);\n"
    "    if (actionMatch) {\n"
    "      tokens.push({ text: actionMatch[0], color: '#5fd0a5' }); /* зелений */\n"
    "      c = c.slice(actionMatch[0].length);\n"
    "    }\n\n"
    "    /* 3. Параметри key=value */\n"
    "    var paramRe = /(\\s*)(\\w[\\w\\-]*)=(\"[^\"]*\"|[^\\s]*)/g;\n"
    "    var lastIdx  = 0;\n"
    "    var match;\n"
    "    while ((match = paramRe.exec(c)) !== null) {\n"
    "      /* Текст між параметрами */\n"
    "      if (match.index > lastIdx) {\n"
    "        tokens.push({ text: c.slice(lastIdx, match.index), color: '#8ea3b0' });\n"
    "      }\n"
    "      tokens.push({ text: match[2], color: '#f0a840' }); /* ключ — жовтий */\n"
    "      tokens.push({ text: '=',      color: '#4a6070' });\n"
    "      /* Значення — різний колір */\n"
    "      var val = match[3];\n"
    "      var valColor = '#e6edf3'; /* білий за замовч */\n"
    "      if (val === 'yes' || val === 'no' || val === 'true' || val === 'false')\n"
    "        valColor = '#c084fc'; /* фіолетовий для bool */\n"
    "      else if (/^\\d+(\\.\\d+)*(\\/\\d+)?$/.test(val))\n"
    "        valColor = '#60a5fa'; /* блакитний для IP/числа */\n"
    "      else if (val === 'accept' || val === 'drop' || val === 'reject')\n"
    "        valColor = (val === 'accept') ? '#5fd0a5' : '#e08080'; /* зелений/червоний */\n"
    "      else if (val === 'input' || val === 'output' || val === 'forward')\n"
    "        valColor = '#f0c060'; /* жовтий для chain */\n"
    "      tokens.push({ text: val, color: valColor });\n"
    "      lastIdx = match.index + match[0].length;\n"
    "    }\n"
    "    if (lastIdx < c.length) {\n"
    "      tokens.push({ text: c.slice(lastIdx), color: '#8ea3b0' });\n"
    "    }\n"
    "    return tokens;\n"
    "  },\n\n"

    "  /* ── Оновити шар підсвітки ── */\n"
    "  updateHighlight: function(val) {\n"
    "    var el = document.getElementById('termlog-highlight');\n"
    "    if (!el) return;\n"
    "    if (!val) { el.innerHTML = ''; return; }\n"
    "    var tokens = TermLog._tokenize(val);\n"
    "    el.innerHTML = tokens.map(function(t) {\n"
    "      var safe = t.text\n"
    "        .replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');\n"
    "      return '<span style=\"color:' + t.color + ';\">' + safe + '</span>';\n"
    "    }).join('');\n"
    "  },\n\n"

    "  /* ── Знайти найкращий autocomplete ── */\n"
    "  getNextCompletion: function(val) {\n"
    "    if (!val || val.length < 2) return null;\n"
    "    var v = val.toLowerCase();\n"
    "    /* 1. Шукаємо в базі команд */\n"
    "    var match = TermLog._rosCommands.find(function(c) {\n"
    "      return c.toLowerCase().startsWith(v) && c.length > v.length;\n"
    "    });\n"
    "    if (match) return match;\n"
    "    /* 2. Шукаємо в параметрах якщо команда вже введена */\n"
    "    var parts = val.split(' ');\n"
    "    if (parts.length >= 2) {\n"
    "      var base = parts.slice(0, -1).join(' ');\n"
    "      var last = parts[parts.length - 1];\n"
    "      /* Параметри для цієї команди */\n"
    "      var params = TermLog._rosParams[base] || '';\n"
    "      var paramList = params.split(' ').filter(Boolean);\n"
    "      var pm = paramList.find(function(p) {\n"
    "        return p.toLowerCase().startsWith(last.toLowerCase()) && p.length > last.length;\n"
    "      });\n"
    "      if (pm) return base + ' ' + pm;\n"
    "    }\n"
    "    /* 3. Шукаємо в історії */\n"
    "    var hist = (TermLog._history || []).slice().reverse();\n"
    "    return hist.find(function(h) {\n"
    "      return h.toLowerCase().startsWith(v) && h.length > v.length;\n"
    "    }) || null;\n"
    "  },\n\n"

    "  /* ── Оновити inline hint (ghost text) ── */\n"
    "  updateHint: function(val) {\n"
    "    var hintEl = document.getElementById('termlog-hint');\n"
    "    if (!hintEl) return;\n"
    "    if (!val || val.length < 2) {\n"
    "      hintEl.textContent = '';\n"
    "      TermLog._currentHint = '';\n"
    "      return;\n"
    "    }\n"
    "    var completion = TermLog.getNextCompletion(val);\n"
    "    if (completion && completion.startsWith(val)) {\n"
    "      /* Показуємо тільки ту частину що ще не введена */\n"
    "      hintEl.textContent = completion;\n"
    "      TermLog._currentHint = completion;\n"
    "    } else {\n"
    "      hintEl.textContent = '';\n"
    "      TermLog._currentHint = '';\n"
    "    }\n"
    "  },\n\n"

    "  /* ── Перехоплення sshCall ── */"
)

if old_intercept in tl:
    tl = tl.replace(old_intercept, new_methods)
    print('OK: _tokenize, updateHighlight, updateHint, getNextCompletion ✅')

with open('ai-agent/terminal-log.js', 'w', encoding='utf-8') as f:
    f.write(tl)

r = subprocess.run(['node','--check','ai-agent/terminal-log.js'],
                   capture_output=True, text=True)
print('terminal-log:', 'OK ✅' if r.returncode==0 else '❌\n'+r.stderr[:200])

print('\nВсе готово! npm start')