# -*- coding: utf-8 -*-
import subprocess

with open('ai-agent/terminal-log.js', 'r', encoding='utf-8') as f:
    tl = f.read()

# Знаходимо Tab handler і переписуємо повністю
old_tab = (
    "      /* Tab — приймаємо autocomplete */\n"
    "      if (e.key === 'Tab') {\n"
    "        e.preventDefault();\n"
    "        var hint = TermLog._currentHint || '';\n"
    "        if (hint && hint.startsWith(this.value)) {\n"
    "          this.value = hint;\n"
    "          TermLog._currentHint = '';\n"
    "          document.getElementById('termlog-hint').textContent = '';\n"
    "          TermLog.updateHighlight(this.value);\n"
    "        } else {\n"
    "          /* Якщо hint не повний — доповнюємо до наступного пробілу */\n"
    "          var next = TermLog.getNextCompletion(this.value);\n"
    "          if (next) { this.value = next; TermLog.updateHighlight(next); }\n"
    "        }\n"
    "        return;\n"
    "      }"
)

new_tab = (
    "      /* Tab — Winbox-стиль autocomplete */\n"
    "      if (e.key === 'Tab') {\n"
    "        e.preventDefault();\n"
    "        var cur = this.value;\n"
    "        /* Знаходимо всі варіанти */\n"
    "        var variants = TermLog.getAllCompletions(cur);\n"
    "        if (variants.length === 0) return;\n"
    "        if (variants.length === 1) {\n"
    "          /* Єдиний варіант — одразу вставляємо + пробіл */\n"
    "          this.value = variants[0] + ' ';\n"
    "          TermLog._currentHint = '';\n"
    "          TermLog._tabVariants = [];\n"
    "          TermLog._tabIdx = 0;\n"
    "          TermLog.updateHighlight(this.value);\n"
    "          TermLog.updateHint(this.value);\n"
    "          TermLog.hideDropdown();\n"
    "        } else {\n"
    "          /* Кілька варіантів — показуємо dropdown */\n"
    "          /* Спершу знаходимо спільний префікс */\n"
    "          var common = variants.reduce(function(a, b) {\n"
    "            var i = 0;\n"
    "            while (i < a.length && i < b.length && a[i] === b[i]) i++;\n"
    "            return a.slice(0, i);\n"
    "          });\n"
    "          if (common.length > cur.length) {\n"
    "            /* Є спільний префікс — доповнюємо до нього */\n"
    "            this.value = common;\n"
    "            TermLog.updateHighlight(this.value);\n"
    "          }\n"
    "          TermLog._tabVariants = variants;\n"
    "          TermLog._tabIdx = -1;\n"
    "          TermLog.showDropdown(variants, this);\n"
    "        }\n"
    "        return;\n"
    "      }\n"
    "      /* Escape — ховаємо dropdown */\n"
    "      if (e.key === 'Escape') {\n"
    "        TermLog.hideDropdown();\n"
    "        return;\n"
    "      }"
)

if old_tab in tl:
    tl = tl.replace(old_tab, new_tab)
    print('OK: Tab Winbox-стиль ✅')
else:
    print('WARN: Tab handler не знайдено')

# Додаємо методи dropdown і getAllCompletions
old_update_hint = "  /* ── Оновити inline hint (ghost text) ── */"

new_methods = (
    "  /* ── Всі варіанти autocomplete ── */\n"
    "  getAllCompletions: function(val) {\n"
    "    if (!val || val.length < 1) return [];\n"
    "    var v = val.toLowerCase();\n"
    "    var results = [];\n"
    "    /* Шукаємо в командах */\n"
    "    TermLog._rosCommands.forEach(function(c) {\n"
    "      if (c.toLowerCase().startsWith(v) && c !== val) results.push(c);\n"
    "    });\n"
    "    /* Якщо є пробіл — шукаємо параметри */\n"
    "    var parts = val.split(' ');\n"
    "    if (parts.length >= 2) {\n"
    "      /* Базова команда (без останнього слова) */\n"
    "      var base = parts.slice(0,-1).join(' ');\n"
    "      var last = parts[parts.length-1].toLowerCase();\n"
    "      /* Шукаємо в параметрах */\n"
    "      var paramStr = '';\n"
    "      /* Перебираємо від довгої до короткої */\n"
    "      Object.keys(TermLog._rosParams).forEach(function(key) {\n"
    "        if (base.toLowerCase().startsWith(key.toLowerCase())) {\n"
    "          paramStr = TermLog._rosParams[key];\n"
    "        }\n"
    "      });\n"
    "      if (paramStr) {\n"
    "        paramStr.split(' ').filter(Boolean).forEach(function(p) {\n"
    "          if (p.toLowerCase().startsWith(last) && p !== last) {\n"
    "            results.push(base + ' ' + p);\n"
    "          }\n"
    "        });\n"
    "      }\n"
    "      /* Популярні значення для відомих параметрів */\n"
    "      var lastLow = last.toLowerCase();\n"
    "      var knownValues = {\n"
    "        'chain=':   ['input','forward','output'],\n"
    "        'action=':  ['accept','drop','reject','masquerade','dst-nat','src-nat','log','passthrough'],\n"
    "        'protocol=':['tcp','udp','icmp','icmpv6'],\n"
    "        'disabled=':['yes','no'],\n"
    "      };\n"
    "      Object.keys(knownValues).forEach(function(key) {\n"
    "        if (lastLow.startsWith(key)) {\n"
    "          var typed = last.slice(key.length).toLowerCase();\n"
    "          knownValues[key].forEach(function(v) {\n"
    "            if (v.startsWith(typed)) {\n"
    "              results.push(base + ' ' + key + v);\n"
    "            }\n"
    "          });\n"
    "        }\n"
    "      });\n"
    "    }\n"
    "    /* Додаємо з історії */\n"
    "    (TermLog._history||[]).slice().reverse().forEach(function(h) {\n"
    "      if (h.toLowerCase().startsWith(v) && h !== val &&\n"
    "          results.indexOf(h) < 0) {\n"
    "        results.push(h);\n"
    "      }\n"
    "    });\n"
    "    return results.slice(0, 10); /* макс 10 варіантів */\n"
    "  },\n\n"

    "  /* ── Dropdown список варіантів ── */\n"
    "  showDropdown: function(variants, inputEl) {\n"
    "    TermLog.hideDropdown();\n"
    "    var bar  = document.getElementById('termlog-input-bar');\n"
    "    if (!bar) return;\n"
    "    var drop = document.createElement('div');\n"
    "    drop.id  = 'termlog-dropdown';\n"
    "    drop.style.cssText = [\n"
    "      'position:absolute', 'bottom:100%', 'left:0', 'right:0',\n"
    "      'background:#0d1117', 'border:1px solid #2a3b48',\n"
    "      'border-radius:8px 8px 0 0', 'z-index:999999',\n"
    "      'max-height:220px', 'overflow-y:auto',\n"
    "      'box-shadow:0 -4px 20px rgba(0,0,0,.5)',\n"
    "    ].join(';');\n"
    "    var activeIdx = -1;\n"
    "    variants.forEach(function(v, i) {\n"
    "      var item = document.createElement('div');\n"
    "      item.style.cssText = [\n"
    "        'padding:5px 14px', 'cursor:pointer',\n"
    "        'font-family:monospace', 'font-size:12px',\n"
    "        'color:#c9d8e4', 'border-bottom:1px solid #1a2a38',\n"
    "        'display:flex', 'align-items:center', 'gap:8px',\n"
    "      ].join(';');\n"
    "      /* Підсвічуємо введену частину */\n"
    "      var cur  = inputEl.value;\n"
    "      var safe = v.replace(/&/g,'&amp;').replace(/</g,'&lt;');\n"
    "      var safeC = cur.replace(/&/g,'&amp;').replace(/</g,'&lt;');\n"
    "      if (safe.toLowerCase().startsWith(safeC.toLowerCase())) {\n"
    "        item.innerHTML =\n"
    "          '<span style=\"color:#5b9bd5;\">' + safe.slice(0, cur.length) + '</span>' +\n"
    "          '<span style=\"color:#5fd0a5;\">' + safe.slice(cur.length) + '</span>';\n"
    "      } else {\n"
    "        item.innerHTML = safe;\n"
    "      }\n"
    "      /* Клік — вставляємо */\n"
    "      item.onclick = function() {\n"
    "        inputEl.value = v + ' ';\n"
    "        TermLog.hideDropdown();\n"
    "        TermLog.updateHighlight(inputEl.value);\n"
    "        TermLog.updateHint(inputEl.value);\n"
    "        inputEl.focus();\n"
    "      };\n"
    "      item.onmouseenter = function() {\n"
    "        this.style.background = '#1a2a38';\n"
    "        activeIdx = i;\n"
    "      };\n"
    "      item.onmouseleave = function() {\n"
    "        this.style.background = '';\n"
    "      };\n"
    "      drop.appendChild(item);\n"
    "    });\n"
    "    bar.style.position = 'relative';\n"
    "    bar.appendChild(drop);\n"
    "    /* Стрілки в dropdown */\n"
    "    TermLog._dropdownActive = true;\n"
    "    TermLog._dropdownEl = drop;\n"
    "    TermLog._dropdownItems = Array.from(drop.children);\n"
    "    TermLog._dropdownVariants = variants;\n"
    "    TermLog._dropdownInput = inputEl;\n"
    "    TermLog._dropdownIdx = -1;\n\n"
    "    /* Навігація стрілками коли dropdown відкритий */\n"
    "    TermLog._dropdownKeyFn = function(e) {\n"
    "      if (!TermLog._dropdownActive) return;\n"
    "      var items = TermLog._dropdownItems;\n"
    "      if (e.key === 'ArrowDown') {\n"
    "        e.preventDefault();\n"
    "        if (TermLog._dropdownIdx >= 0)\n"
    "          items[TermLog._dropdownIdx].style.background = '';\n"
    "        TermLog._dropdownIdx = Math.min(TermLog._dropdownIdx+1, items.length-1);\n"
    "        items[TermLog._dropdownIdx].style.background = '#1a3a2a';\n"
    "        items[TermLog._dropdownIdx].style.color = '#5fd0a5';\n"
    "      } else if (e.key === 'ArrowUp') {\n"
    "        e.preventDefault();\n"
    "        if (TermLog._dropdownIdx >= 0)\n"
    "          items[TermLog._dropdownIdx].style.background = '';\n"
    "        TermLog._dropdownIdx = Math.max(TermLog._dropdownIdx-1, 0);\n"
    "        items[TermLog._dropdownIdx].style.background = '#1a3a2a';\n"
    "        items[TermLog._dropdownIdx].style.color = '#5fd0a5';\n"
    "      } else if (e.key === 'Enter' || e.key === 'Tab') {\n"
    "        e.preventDefault();\n"
    "        if (TermLog._dropdownIdx >= 0) {\n"
    "          var chosen = TermLog._dropdownVariants[TermLog._dropdownIdx];\n"
    "          TermLog._dropdownInput.value = chosen + ' ';\n"
    "          TermLog.updateHighlight(chosen + ' ');\n"
    "          TermLog.updateHint(chosen + ' ');\n"
    "        }\n"
    "        TermLog.hideDropdown();\n"
    "        TermLog._dropdownInput.focus();\n"
    "      } else if (e.key === 'Escape') {\n"
    "        TermLog.hideDropdown();\n"
    "      }\n"
    "    };\n"
    "    document.addEventListener('keydown', TermLog._dropdownKeyFn, true);\n"
    "  },\n\n"

    "  hideDropdown: function() {\n"
    "    var old = document.getElementById('termlog-dropdown');\n"
    "    if (old) old.remove();\n"
    "    TermLog._dropdownActive = false;\n"
    "    if (TermLog._dropdownKeyFn) {\n"
    "      document.removeEventListener('keydown', TermLog._dropdownKeyFn, true);\n"
    "      TermLog._dropdownKeyFn = null;\n"
    "    }\n"
    "  },\n\n"

    "  /* ── Оновити inline hint (ghost text) ── */"
)

if old_update_hint in tl:
    tl = tl.replace(old_update_hint, new_methods)
    print('OK: getAllCompletions + dropdown + hideDropdown ✅')

# Ховаємо dropdown при кліку поза ним
old_init_end = "    TermLog._history = [];\n    TermLog._histIdx = 0;"
new_init_end = (
    "    TermLog._history = [];\n"
    "    TermLog._histIdx = 0;\n"
    "    /* Ховаємо dropdown при кліку поза */\n"
    "    document.addEventListener('click', function(e) {\n"
    "      var dd = document.getElementById('termlog-dropdown');\n"
    "      if (dd && !dd.contains(e.target) &&\n"
    "          e.target.id !== 'termlog-cmd-input') {\n"
    "        TermLog.hideDropdown();\n"
    "      }\n"
    "    });"
)
if old_init_end in tl:
    tl = tl.replace(old_init_end, new_init_end)
    print('OK: click outside ✅')

with open('ai-agent/terminal-log.js', 'w', encoding='utf-8') as f:
    f.write(tl)

r = subprocess.run(['node','--check','ai-agent/terminal-log.js'],
                   capture_output=True, text=True)
print('terminal-log:', 'OK ✅' if r.returncode==0 else '❌\n'+r.stderr[:200])
print('\nВсе готово! npm start')